#+title: Emax Configuration
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el

* Package Foundation

** Straight + use-package
#+begin_src emacs-lisp
(defvar bootstrap-version)
(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'use-package)
(use-package straight
             :custom (straight-use-package-by-default t))
#+end_src

* Initial Setup

Setting required to make sure evil setup can happen without hiccups later.

#+begin_src emacs-lisp
(setq evil-want-keybinding nil)
#+end_src

* Theme

** Colors

Loading
#+begin_src emacs-lisp
(load "~/.emacs.d/themes/github-dark-theme.el")
(load "~/.emacs.d/themes/github-light-theme.el")
#+end_src

Utilize ~auto-dark~ to adjust theme automatically when macOS switches
between dark and light themes.
#+begin_src emacs-lisp
(use-package auto-dark
  :custom
  (auto-dark-dark-theme 'github-dark)
  (auto-dark-light-theme 'github-light))
#+end_src

Adjusting minibuffer background depending on the theme.  This is
necessary, as otherwise the minibuffer has the same color as normal
buffers and doesn't really separate visually.
#+begin_src emacs-lisp
(defun mk/minibuffer-dark-bg ()
  (set (make-local-variable 'face-remapping-alist)
       '((default :background "#444d56"))))

(defun mk/minibuffer-light-bg ()
  (set (make-local-variable 'face-remapping-alist)
       '((default :background "#d7d7d7"))))
#+end_src

Provide functions to quickly switch between dark and light theme.
#+begin_src emacs-lisp
(defun mk/dark-theme ()
  (interactive)
  (remove-hook 'minibuffer-setup-hook 'mk/minibuffer-light-bg)
  (add-hook 'minibuffer-setup-hook 'mk/minibuffer-dark-bg))

(defun mk/light-theme ()
  (interactive)
  (remove-hook 'minibuffer-setup-hook 'mk/minibuffer-dark-bg)
  (add-hook 'minibuffer-setup-hook 'mk/minibuffer-light-bg))
#+end_src

Acutally triggering minibuffer background adjustments after color
change.
#+begin_src emacs-lisp
(add-hook 'auto-dark-dark-mode-hook 'mk/dark-theme)
(add-hook 'auto-dark-light-mode-hook 'mk/light-theme)
#+end_src

The ~auto-dark~ mode can only be enabled when we have a frame.
#+begin_src emacs-lisp
(add-hook 'after-make-frame-functions
  (lambda (frame)
    (select-frame frame)
    (when (display-graphic-p frame)
      (auto-dark-mode t))))
#+end_src

** Layout

Use Nano layout.
#+begin_src emacs-lisp
(straight-use-package
    '(nano-emacs :type git :host github :repo "rougier/nano-emacs"))
(require 'nano-layout)
#+end_src

Use Nano modeline
#+begin_src emacs-lisp
(straight-use-package
    '(nano-modeline :type git :host github :repo "rougier/nano-modeline"))
(nano-modeline-mode)
#+end_src

** Fonts
#+begin_src emacs-lisp
(set-face-attribute 'default nil
  :family "Roboto Mono"
  :height 150
  :weight 'medium
  :width 'normal)
#+end_src

** General UI

Hide various bars.
#+begin_src emacs-lisp
(tool-bar-mode -1)
(scroll-bar-mode -1)
#+end_src

Enable relative line numbers.
#+begin_src emacs-lisp
(global-display-line-numbers-mode t)
(setq display-line-numbers-type 'relative)
(add-hook 'term-mode-hook (lambda () (display-line-numbers-mode 0)))
#+end_src

Set line spacing.
#+begin_src emacs-lisp
(setq-default line-spacing 2)
(setq default-text-properties '(line-spacing 0.2 line-height 1.2))
#+end_src

Enable line highlighting
#+begin_src emacs-lisp
(global-hl-line-mode 1)
#+end_src

* Completion: Search/Navigation

#+begin_src emacs-lisp
(use-package consult)
#+end_src

For fuzzy matching in searches.
#+begin_src emacs-lisp
(use-package orderless
  :ensure t
  :custom
  (completion-styles '(orderless basic))
  (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src

#+begin_src emacs-lisp
(use-package vertico
  :init
  (vertico-mode)

  ;; Different scroll margin
  ;; (setq vertico-scroll-margin 0)

  ;; Show more candidates
  ;; (setq vertico-count 20)

  ;; Grow and shrink the Vertico minibuffer
  ;; (setq vertico-resize t)

  ;; Optionally enable cycling for `vertico-next' and `vertico-previous'.
  ;; (setq vertico-cycle t)
  )
#+end_src

Enable rich annotations in completion interfaces.
#+begin_src emacs-lisp
(use-package marginalia
  ;; Either bind `marginalia-cycle' globally or only in the minibuffer
  :bind (("M-A" . marginalia-cycle)
         :map minibuffer-local-map
         ("M-A" . marginalia-cycle))

  ;; The :init configuration is always executed (Not lazy!)
  :init

  ;; Must be in the :init section of use-package such that the mode gets
  ;; enabled right away. Note that this forces loading the package.
  (marginalia-mode))
#+end_src

Alternative interface for M-x.
#+begin_src emacs-lisp
(use-package amx
  :config
  (amx-mode))
#+end_src

* Completion: Text/Code
#+begin_src emacs-lisp
(use-package company)
(add-hook 'after-init-hook 'global-company-mode)
(setq company-idle-delay 0.2)
(setq company-dabbrev-downcase nil)
#+end_src

Merge company backends
#+begin_src emacs-lisp
(defun mk/company-backends-hook ()
  (interactive)
  (message "mk/ Hooking backends...")
  (setq company-backends
  '((company-dabbrev
     company-dabbrev-code
     company-capf
     company-files
     company-keywords
     company-clang
     company-gtags
     company-etags
     company-semantic
     company-bbdb
     :separate))))
(add-hook 'text-mode-hook 'mk/company-backends-hook)
(add-hook 'prog-mode-hook 'mk/company-backends-hook)
(add-hook 'eglot-managed-mode-hook (lambda () (mk/company-backends-hook)))
#+end_src

Autocomplete / adjust parentheses.
#+begin_src emacs-lisp
(use-package smartparens
  :config
  (sp-pair "$" "$")
  (smartparens-global-mode t))
#+end_src

* Files

Use dirvish as a dired alternative.
#+begin_src emacs-lisp
(use-package dirvish
  :config
  (dirvish-override-dired-mode))
#+end_src

* Git
Use magit
#+begin_src emacs-lisp
(use-package magit)
#+end_src

Use magit-delta for better diffing.
#+begin_src emacs-lisp
(use-package magit-delta)
(add-hook 'magit-mode-hook (lambda () (magit-delta-mode +1)))
#+end_src

Display diff indicators in the gutter.
#+begin_src emacs-lisp
(use-package git-gutter
  :config
  (add-hook 'prog-mode-hook (lambda () (git-gutter-mode)))
  (add-hook 'TeX-mode-hook (lambda () (git-gutter-mode)))
  (setq git-gutter:update-interval 0.02))

(use-package git-gutter-fringe
  :config
  (define-fringe-bitmap 'git-gutter-fr:added [224] nil nil '(center repeated))
  (define-fringe-bitmap 'git-gutter-fr:modified [224] nil nil '(center repeated))
  (define-fringe-bitmap 'git-gutter-fr:deleted [128 192 224 240] nil nil 'bottom)
  (set-face-foreground 'git-gutter-fr:modified "dodger blue")
  (set-face-foreground 'git-gutter-fr:added    "sea green")
  (set-face-foreground 'git-gutter-fr:deleted  "red2"))
#+end_src

* Programming

** Bibtex

Use citar to insert citations from the bib-file.
#+begin_src emacs-lisp
(use-package citar
  :bind (("C-c b" . citar-insert-citation)
         :map minibuffer-local-map
         ("M-b" . citar-insert-preset)))
#+end_src

We use a custom function for Bibtex key generation.
#+begin_src emacs-lisp
(require 'cl-lib)
(setq bibtex-autokey-before-presentation-function
  (lambda
    (key)
    (concat
     (seq-subseq key 0
                 (cl-search "-" key))
     "-"
     (seq-subseq key
             (+
              ;; TODO: We need to handle the case where we get nil here.
              (cl-search "-" key)
              4))
     "-"
     (seq-subseq key
             (+
              ;; TODO: We need to handle the case where we get nil here.
              (cl-search "-" key)
              1)
             (+
              ;; TODO: We need to handle the case where we get nil here.
              (cl-search "-" key)
              3)))))

(setq bibtex-autokey-name-length -1)
(setq bibtex-autokey-name-year-separator "-")
(setq bibtex-autokey-names 3)
(setq bibtex-autokey-names-stretch 1)
(setq bibtex-autokey-titleword-length -1)
(setq bibtex-autokey-titleword-separator "")
(setq bibtex-autokey-year-title-separator "-")
#+end_src

Enable line numbers in Bibtex mode by default.
#+begin_src emacs-lisp
(add-hook 'bibtex-mode-hook (lambda ()
                              (display-line-numbers-mode)
                              (setq display-line-numbers 'relative)))
#+end_src

Enable Reftex in AUCTeX and fix an issue where reftex won't
search/find the bib-file initially.
#+begin_src emacs-lisp
(add-hook 'TeX-mode-hook (lambda ()
   (turn-on-reftex)
   (reftex-parse-all)))
#+end_src

Enable a nice interface between RefTeX and AUCTeX
#+begin_src emacs-lisp
(setq reftex-plug-into-AUCTeX t)
#+end_src

Tell RefTeX where it should look for bib files.
#+begin_src emacs-lisp
(setq reftex-external-file-finders
      '(("tex" . "kpsewhich -format=.tex %f")
        ("bib" . "kpsewhich -format=.bib %f")))
(setq reftex-use-external-file-finders t)
#+end_src

** Latex

#+begin_src emacs-lisp
(straight-use-package 'auctex)
#+end_src

Make sure we find the correct TeX binaries.
#+begin_src emacs-lisp
(setenv "PATH" (concat (getenv "PATH") ":/Library/TeX/texbin/"))
(setq exec-path (append exec-path '("/Library/TeX/texbin/")))
#+end_src

Enable LSP in Latex
#+begin_src emacs-lisp
(add-hook 'TeX-mode-hook 'eglot-ensure)
#+end_src

Use LatexMk
#+begin_src emacs-lisp
(use-package auctex-latexmk
  :config
  (setq auctex-latexmk-inherit-TeX-PDF-mode t)
  (auctex-latexmk-setup)
  (setq TeX-command-default "LatexMk")
  (setq latex-build-command "LatexMk")
  (setq LaTeX-electric-left-right-brace t)) ; Enable left/right auto-complete
#+end_src

A nice build command that uses LatexMk
#+begin_src emacs-lisp
(defun latex/build ()
  (interactive)
  (progn
    (let ((TeX-save-query nil))
      (TeX-save-document (TeX-master-file)))
    (TeX-command latex-build-command 'TeX-master-file -1)))
#+end_src

Functions to change latex font environments (bold, emphasis, etc.)
#+begin_src emacs-lisp
(defun latex/font-bold () (interactive) (TeX-font nil ?\C-b))
(defun latex/font-medium () (interactive) (TeX-font nil ?\C-m))
(defun latex/font-code () (interactive) (TeX-font nil ?\C-t))
(defun latex/font-emphasis () (interactive) (TeX-font nil ?\C-e))
(defun latex/font-italic () (interactive) (TeX-font nil ?\C-i))
(defun latex/font-clear () (interactive) (TeX-font nil ?\C-d))
(defun latex/font-calligraphic () (interactive) (TeX-font nil ?\C-a))
(defun latex/font-small-caps () (interactive) (TeX-font nil ?\C-c))
(defun latex/font-sans-serif () (interactive) (TeX-font nil ?\C-f))
(defun latex/font-normal () (interactive) (TeX-font nil ?\C-n))
(defun latex/font-serif () (interactive) (TeX-font nil ?\C-r))
(defun latex/font-oblique () (interactive) (TeX-font nil ?\C-s))
(defun latex/font-upright () (interactive) (TeX-font nil ?\C-u))
#+end_src

Setup synctex
#+begin_src emacs-lisp
(setq TeX-source-correlate-mode t)
(setq TeX-source-correlate-start-server t)
(setq TeX-source-correlate-method 'synctex)
#+end_src

Use Skim for latex previews
#+begin_src emacs-lisp
(setq TeX-view-program-list
      '(("Skim" "/Applications/Skim.app/Contents/SharedSupport/displayline -b -g %n %o %b")))
(setq TeX-view-program-selection '((output-pdf "Skim")))
#+end_src

In latex we want to adjust the fill-column.
#+begin_src emacs-lisp
(add-hook 'TeX-mode-hook (lambda ()
                           (setq fill-column 70)))
#+end_src

** Markdown
#+begin_src emacs-lisp
(use-package markdown-mode
  :ensure t
  :mode ("README\\.md\\'" . gfm-mode)
  :init (setq markdown-command "multimarkdown"))
#+end_src
** Org
#+begin_src emacs-lisp
(use-package org)
#+end_src

A modern look for org.
#+begin_src emacs-lisp
(use-package org-modern
  :hook ((org-mode . org-modern-mode)
         (org-agenda-finalize . org-modern-agenda)))
#+end_src

*** Tempo

Use tempo to automatically extend shortcuts into src blocks. (e.g.,
type “<el” and hit TAB)
#+begin_src emacs-lisp
(require 'org-tempo)
(add-to-list 'org-structure-template-alist '("bib" . "src bibtex"))
(add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
(add-to-list 'org-structure-template-alist '("py" . "src python"))
(add-to-list 'org-structure-template-alist '("sh" . "src shell"))
(add-to-list 'org-structure-template-alist '("tex" . "src latex"))
(add-to-list 'org-structure-template-alist '("ein" . "src ein-python :session localhost"))
(add-to-list 'org-structure-template-alist '("r" . "src R :session :exports both results output org"))
#+end_src

*** Babel
Used to execute code in org buffers.
#+begin_src emacs-lisp
(org-babel-do-load-languages
  'org-babel-load-languages
    '((emacs-lisp . t)
      (python . t)
      (R . t)))
#+end_src

Do not ask for confirmation when evaluating code with babel.
#+begin_src emacs-lisp
(setq org-confirm-babel-evaluate nil)
#+end_src

Use babel to convert this ~config.org~ file into the ~init.el~ file.
#+begin_src emacs-lisp
(defun mk/org-babel-tangle-config ()
  (when (string-equal (buffer-file-name)
                      (expand-file-name "~/.emacs.d/config.org"))
    (let ((org-confirm-babel-evaluate nil))
      (org-babel-tangle))))
(add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'mk/org-babel-tangle-config)))
#+end_src

** Python
#+begin_src emacs-lisp
(use-package python-mode
  :init
  (add-hook 'python-mode-hook 'eglot-ensure)) ;; Enable LSP in Python
#+end_src

* LSP

Define which LSP providers should be used in which mode.
#+begin_src emacs-lisp
(with-eval-after-load 'eglot
  (add-to-list 'eglot-server-programs
               '(python-mode . ("pylsp"))))
#+end_src

* Windows

** Splitting

Functions for splitting windows.
#+begin_src emacs-lisp
(defun split-and-follow-vertically ()
  (interactive)
  (split-window-right)
  (balance-windows)
  (other-window 1))

(defun split-and-follow-horizontally ()
  (interactive)
  (split-window-below)
  (balance-windows)
  (other-window 1))
  
(defun mk/split-to-shell ()
  "If no *shell* buffer exists, one is created using the `shell` function
  and it is displayed in a new window at the ver bottom. If such a window is
  shown already, it is deleted instead."
  (interactive)
  (let ((shell-window (get-buffer-window "*shell*")))
    (if shell-window
       (progn
         (delete-window shell-window))
        (progn
        (split-and-follow-horizontally)
        (evil-window-move-very-bottom)
        (unless (get-buffer "*shell*")
          (shell))
        (switch-to-buffer "*shell*")))))

(defun mk/split-to-shell-fullscreen ()
  (interactive)
  (mk/split-to-shell)
  (delete-other-windows))
#+end_src

* Utilities

** Colors
Highlight hex-colors
#+begin_src emacs-lisp
(use-package rainbow-mode)
#+end_src

** Help
Provide help for functions/variables.
#+begin_src emacs-lisp
(use-package helpful)
#+end_src

** General

Don't store cut content in clipboard.
#+begin_src emacs-lisp
(setq-default evil-kill-on-visual-paste nil)
#+end_src

** Files
Include recent files when switching between buffers.
#+begin_src emacs-lisp
(recentf-mode 1)
(setq recentf-max-menu-items 25)
(setq recentf-max-saved-items 25)
#+end_src
** Search
Use ripgrep for search!
#+begin_src emacs-lisp
(use-package rg)
#+end_src
* Keybindings

#+begin_src emacs-lisp
(setq mac-option-modifier 'alt)
(setq mac-command-modifier 'meta)
(global-set-key (kbd "A-<backspace>") 'backward-kill-word)
(global-set-key (kbd "<escape>") 'keyboard-escape-quit)
#+end_src

** Evil
#+begin_src emacs-lisp
(use-package evil
  :init
  (setq evil-want-keybinding nil) ;; Required for evil-collection
  (setq evil-want-visual-char-semi-exclusive t)
  :config
  (evil-mode 1))
#+end_src

Use j/k to jump up and down in the current column, even if lines are
wrapped.
#+begin_src emacs-lisp
(define-key evil-normal-state-map (kbd "j") 'evil-next-visual-line)
(define-key evil-normal-state-map (kbd "k") 'evil-previous-visual-line)
#+end_src

Use evil throughout various tools in emacs.
#+begin_src emacs-lisp
(use-package evil-collection
  :after evil
  :config
  (evil-collection-init))
#+end_src

Swap expressions using evil keybindings.
#+begin_src emacs-lisp
(use-package evil-exchange
  :config
  (evil-exchange-install))
#+end_src

Use evil-matchit to jump between tags (e.g. begin/end in Latex)
#+begin_src emacs-lisp
(use-package evil-matchit
  :init
  (global-evil-matchit-mode 1))
#+end_src

** Miscellaneous
Display currently available keybindings.
#+begin_src emacs-lisp
(use-package which-key
  :config
  (which-key-setup-minibuffer)
  (which-key-mode))
#+end_src

Use hydra to generate keyboard-driven menus.
#+begin_src emacs-lisp
(use-package hydra)
#+end_src

Packages related to getting a spacemacs-like setup.
#+begin_src emacs-lisp
(use-package dash)
(use-package general)
(use-package bind-map)
(use-package bind-key)
(straight-use-package
 '(spaceleader :type git :host github :repo "mohkale/spaceleader"))
#+end_src

** Bindings

*** General
#+begin_src emacs-lisp
(leader-set-keys
  "TAB" '(switch-to-last-buffer+ :wk "last-buffer")
  "SPC" 'execute-extended-command
  "<escape>" 'abort-recursive-edit
  "DEL" 'exit-recursive-edit
  "/" 'consult-ripgrep
)
#+end_src

#+begin_src emacs-lisp
(define-key evil-normal-state-map "/" 'consult-line)
#+end_src

*** Bibtex
#+begin_src emacs-lisp
(leader-set-keys-for-major-mode 'bibtex-mode "s" 'org-ref-sort-bibtex-entry)
(leader-set-keys-for-major-mode 'bibtex-mode "c" 'bibtex-clean-entry)
#+end_src

*** Buffers
Function to create a ~scratch~ buffer.
#+begin_src emacs-lisp
(defun create-scratch-buffer nil
   "create a scratch buffer"
   (interactive)
   (switch-to-buffer (get-buffer-create "*scratch*")))
#+end_src

#+begin_src emacs-lisp
(leader-set-keys
  "b" '(:ignore t :wk "buffers")
  "bb" 'consult-buffer
  "bd" 'kill-this-buffer
  "bn" 'next-buffer
  "bp" 'previous-buffer
  "bs" 'create-scratch-buffer
  "br" 'revert-buffer
)
#+end_src

*** Comments
Function to comment regions without including the last line-break and
thus commenting outside of the selected region.
#+begin_src emacs-lisp
(defun comment-or-uncomment-region-or-line ()
    "Comments or uncomments the region or the current line if there's no active region."
    (interactive)
    (let (beg end)
        (if (region-active-p)
            (setq beg (region-beginning) end (region-end))
            (setq beg (line-beginning-position) end (line-end-position)))
        (comment-or-uncomment-region beg end)))
#+end_src

#+begin_src emacs-lisp
(leader-set-keys
  "c" '(:ignore t :wk "comment")
  "cl" 'comment-or-uncomment-region-or-line
)
#+end_src

*** Dired
#+begin_src emacs-lisp
(leader-set-keys
  "a" '(:ignore t :wk "applications")
  "ad" 'dired-jump
)
#+end_src

*** Eval
#+begin_src emacs-lisp
(leader-set-keys
  "e" '(:ignore t :wk "eval")
  "es" 'eval-last-sexp
)
#+end_src

*** Files

Function to find the ~config.org~ file.
#+begin_src emacs-lisp
(defun mk/find-user-init-file ()
  (interactive)
  (find-file (expand-file-name "~/.emacs.d/config.org")))
#+end_src

#+begin_src emacs-lisp
(leader-set-keys
  "f" '(:ignore t :wk "files")
  "ff" 'ido-find-file
  "fc" 'copy-file
  "fh" 'find-file-at-point
  "fed" 'mk/find-user-init-file
)
#+end_src

*** Git

#+begin_src emacs-lisp
(leader-set-keys
  "g" '(:ignore t :wk "git")
  "gs" 'magit-status
  "gh" 'magit-diff-buffer-file
  "gm" '(:ignore t :wk "merge")
  "gmn" 'smerge-next
  "gmp" 'smerge-prev
  "gma" 'smerge-keep-all
  "gmc" 'smerge-keep-current
  "gmo" 'smerge-keep-other
)
#+end_src

*** Help

#+begin_src emacs-lisp
(leader-set-keys
  "h" '(:ignore t :wk "help")
  "hv" 'helpful-variable
  "hk" 'helpful-key
  "hf" 'helpful-function
  "ht" 'helpful-at-point
)
#+end_src

*** Jumping
#+begin_src emacs-lisp
(leader-set-keys
  "j" '(:ignore t :wk "jump")
  "ji" 'consult-imenu
)
#+end_src

*** Latex
#+begin_src emacs-lisp
(leader-set-keys-for-major-mode 'latex-mode "c" 'latex/build)
(leader-set-keys-for-major-mode 'latex-mode "b" 'TeX-command-master)
(leader-set-keys-for-major-mode 'latex-mode "v" 'TeX-view)
(leader-set-keys-for-major-mode 'latex-mode "m" 'TeX-insert-macro)
(leader-set-keys-for-major-mode 'latex-mode "e" 'LaTeX-environment)
(leader-set-keys-for-major-mode 'latex-mode "l" 'TeX-error-overview)
(leader-set-keys-for-major-mode 'latex-mode "-" 'TeX-recenter-output-buffer)
(leader-set-keys-for-major-mode 'latex-mode "r" 'reftex-reference)
(leader-set-keys-for-major-mode 'latex-mode "s" 'LaTeX-section)
(leader-set-keys-for-major-mode 'latex-mode "C" 'citar-insert-citation)
(leader-set-keys-for-major-mode 'latex-mode "R" 'reftex-toc)
(leader-set-keys-for-major-mode 'latex-mode "xb" 'latex/font-bold)
(leader-set-keys-for-major-mode 'latex-mode "xe" 'latex/font-emphasis)
(leader-set-keys-for-major-mode 'latex-mode "xi" 'latex/font-italic)
(leader-set-keys-for-major-mode 'latex-mode "xc" 'latex/font-code)
(leader-set-keys-for-major-mode 'latex-mode "xs" 'latex/font-small-caps)
#+end_src

*** Macros
#+begin_src emacs-lisp
(leader-set-keys
  "K" '(:ignore t :wk "macros")
  "K" 'kmacro-call-macro
)
#+end_src

*** Python
#+begin_src emacs-lisp
(leader-set-keys-for-major-mode 'python-mode "c" 'compile)
(leader-set-keys-for-major-mode 'python-mode "=" 'yapfify-buffer)
#+end_src

*** Shell
#+begin_src emacs-lisp
(leader-set-keys-for-major-mode 'shell-mode "h" 'counsel-shell-history)
#+end_src

*** Spelling
#+begin_src emacs-lisp
(leader-set-keys
  "S" '(:ignore t :wk "Spelling")
  "Sb" 'flyspell-buffer
  "Sc" 'flyspell-correct-wrapper
  "Sn" 'flyspell-goto-next-error
  "Sd" 'ispell-change-dictionary
)
#+end_src

*** Substitute
#+begin_src emacs-lisp
(leader-set-keys
  "s" '(:ignore t :wk "subsitute")
  "se" '(evil-iedit-state/iedit-mode)
  "sr" 'sp-rewrap-sexp
  "sd" 'sp-splice-sexp
)
#+end_src

*** Text
#+begin_src emacs-lisp
(leader-set-keys
  "x" '(:ignore t :wk "text")
  "xp" 'fill-paragraph
  "xP" 'unfill-paragraph
  "xC" 'capitalize-word
  "xL" 'downcase-word
  "xT" 'titlecase-region
  "xa" 'accent-menu
  "xi" 'hydra-transient-special-characters/body
)
#+end_src

*** Theme
#+begin_src emacs-lisp

#+end_src

*** Toggles
#+begin_src emacs-lisp
(leader-set-keys
  "t" '(:ignore t :wk "toggles")
  "ta" 'auto-fill-mode
  "tl" 'toggle-truncate-lines
)
#+end_src

*** Universal
#+begin_src emacs-lisp
(leader-set-keys
  "u" 'universal-argument
)
#+end_src

*** Windows

Transient state for window resizing.
#+begin_src emacs-lisp
(defhydra hydra-transient-window-resize (:timeout 4)
  "resize window cyclically"
  ("+" mk/enlarge-window "enlarge window")
  ("-" mk/shrink-window "shrink window")
  ("=" balance-windows "balance windows")
  ("s" cycle-resize-window-vertically "resize vertically")
  ("v" cycle-resize-window-horizontally "resize horizontally"))
#+end_src

#+begin_src emacs-lisp
(leader-set-keys
  "w" '(:ignore t :wk "window")
  "wd" 'delete-window
  "wD" 'delete-other-windows
  "wv" 'split-and-follow-vertically
  "ws" 'split-and-follow-horizontally
  "wl" 'evil-window-right
  "wL" 'evil-window-move-far-right
  "wh" 'evil-window-left
  "wH" 'evil-window-move-far-left
  "wj" 'evil-window-down
  "wJ" 'evil-window-move-very-bottom
  "wk" 'evil-window-up
  "wK" 'evil-window-move-very-top
  "wt" 'mk/split-to-shell
  "wT" 'mk/split-to-shell-fullscreen
  "wr" 'hydra-transient-window-resize/body
  "wc" 'writeroom-mode
)
#+end_src

*** Zoom
#+begin_src emacs-lisp
(leader-set-keys
  "z" '(:ignore t :wk "zoom")
  "zx" 'text-scale-adjust
)
#+end_src
